import './api/carto-api-error.spec';
import './api/layer-map.spec';
// import './api/parseMap.spec';
import './api/maps-api-client.spec';
// import './carto-layer.spec';
import './config.spec';
import './utils.spec';
import './layers/carto-vector-tile.spec';
import './layers/h3-tile-layer.spec';
import './layers/h3-tileset-2d.spec';
import './layers/raster.spec';
import './layers/spatialjson.spec';
import './layers/point-label-layer.spec';
import './layers/quadbin-layer.spec';
import './layers/quadbin-tile-layer.spec';
import './layers/quadbin-tileset-2d.spec';
// import './layers/vector-tile-layer.spec';
import './style/carto-color-bins.spec';
import './style/carto-color-categories.spec';
import './style/carto-color-continuous.spec';
import './style/carto-hex-to-rgb.spec';
import './style/carto-palette.spec';
import './style/carto-utils.spec';
