enableScripts: true

nodeLinker: node-modules

logFilters:
  - code: YN0060
    pattern: "*@types/react is listed by your project with version 18.3.28*"
    level: discard
  - code: YN0060
    pattern: "*react is listed by your project with version 18.3.1*"
    level: discard
  - code: YN0060
    pattern: "*react-dom is listed by your project with version 18.3.1*"
    level: discard
  - code: YN0002
    pattern: "*doesn't provide @deck.gl/extensions*"
    level: discard
  - code: YN0002
    pattern: "*doesn't provide @deck.gl/mesh-layers*"
    level: discard
  - code: YN0002
    pattern: "*doesn't provide @loaders.gl/core*"
    level: discard
  - code: YN0002
    pattern: "*doesn't provide @luma.gl/core*"
    level: discard
  - code: YN0002
    pattern: "*doesn't provide @luma.gl/engine*"
    level: discard
  - code: YN0002
    pattern: "*doesn't provide @luma.gl/shadertools*"
    level: discard
  - code: YN0002
    pattern: "*doesn't provide @luma.gl/webgl*"
    level: discard
  - code: YN0002
    pattern: "*doesn't provide @luma.gl/webgpu*"
    level: discard
  - code: YN0002
    pattern: "*doesn't provide esri-loader*"
    level: discard
  - code: YN0002
    pattern: "*doesn't provide react*"
    level: discard
  - code: YN0002
    pattern: "*doesn't provide react-dom*"
    level: discard
  - code: YN0086
    pattern: "*Some peer dependencies are incorrectly met*"
    level: discard
