approvedGitRepositories:
  - "**"

enableScripts: true

logFilters:
  - code: YN0060
    level: discard
    pattern: "*@types/react is listed by your project with version 18.3.28*"
  - code: YN0060
    level: discard
    pattern: "*react is listed by your project with version 18.3.1*"
  - code: YN0060
    level: discard
    pattern: "*react-dom is listed by your project with version 18.3.1*"
  - code: YN0002
    level: discard
    pattern: "*doesn't provide @deck.gl/core*"
  - code: YN0002
    level: discard
    pattern: "*doesn't provide @deck.gl/extensions*"
  - code: YN0002
    level: discard
    pattern: "*doesn't provide @deck.gl/mesh-layers*"
  - code: YN0002
    level: discard
    pattern: "*doesn't provide @loaders.gl/core*"
  - code: YN0002
    level: discard
    pattern: "*doesn't provide @luma.gl/core*"
  - code: YN0002
    level: discard
    pattern: "*doesn't provide @luma.gl/engine*"
  - code: YN0002
    level: discard
    pattern: "*doesn't provide @luma.gl/shadertools*"
  - code: YN0002
    level: discard
    pattern: "*doesn't provide @luma.gl/webgl*"
  - code: YN0002
    level: discard
    pattern: "*doesn't provide @luma.gl/webgpu*"
  - code: YN0002
    level: discard
    pattern: "*doesn't provide esri-loader*"
  - code: YN0002
    level: discard
    pattern: "*doesn't provide react*"
  - code: YN0002
    level: discard
    pattern: "*doesn't provide react-dom*"
  - code: YN0086
    level: discard
    pattern: "*Some peer dependencies are incorrectly met*"

nodeLinker: node-modules

npmMinimalAgeGate: 0
