name: Bug Report
description: Something does not work as expected
title: "[Bug]"
labels: bug
body:
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to report a bug!
      You may find answers faster by searching in [the documentation](https://deck.gl/search) and [existing issues](https://github.com/visgl/deck.gl/issues).
      If you are unsure whether it is a bug in your own implementation or the library itself, consider starting a conversation in [Discussions](https://github.com/visgl/deck.gl/discussions) instead.
- type: textarea
  attributes:
    label: Description
    description: What you're experiencing.
  validations:
    required: true
- type: checkboxes
  id: flavor
  attributes:
    label: Flavors
    description: Are you using one of the following platform-specific APIs?
    options:
      - label: Script tag
      - label: React
      - label: Python/Jupyter notebook
      - label: MapboxOverlay
      - label: GoogleMapsOverlay
      - label: CartoLayer
      - label: ArcGIS
- type: textarea
  attributes:
    label: Expected Behavior
    description: What you expect to see.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps to Reproduce
    description: |
      Providing the following could help us resolve this issue faster:
        - A Codepen that reproduces the behavior. A good starting point is the "edit in CodePen" links in the layer documentations.
        - A sample of your dataset
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment
    description: |
      Example:
        - **Framework version**: deck.gl@8.9.0
        - **Browser**: Chrome 110.0
        - **OS**: iOS 16.3
    value: |
        - Framework version:
        - Browser:
        - OS:
  validations:
    required: true
- type: textarea
  attributes:
    label: Logs
    description: Check the browser console for any relevant errors or warnings.
  validations:
    required: false
