name: Docs Improvement
description: Request for a correction or clarification in the documentation
title: "[Doc]"
labels: doc
body:
- type: input
  attributes:
    label: Link
    description: Link to the current documentation page, if any
  validations:
    required: false
- type: textarea
  attributes:
    label: Description
    description: How can we make it better?
  validations:
    required: true
    
