/**
 * Utilities for opening generated examples in online code playgrounds.
 *
 * CodePen requires a form POST — no direct URL is possible — so we inject
 * a button into the downloaded HTML artifact. When a user opens the file
 * locally and clicks the button, the form POSTs to codepen.io (works from file://).
 *
 * CodeSandbox supports a GET-based define API, so we can embed a direct
 * clickable link in the PR comment itself.
 */
import LZString from 'lz-string';

/**
 * Parse a self-contained HTML example into its component parts.
 * Handles the structure our generation prompt produces:
 *   <head> — external <script src>, <link rel=stylesheet>, inline <style>
 *   <body> — DOM content + inline <script> (the deck.gl setup code)
 */
export function parseExample(html) {
  const jsExternal = [];
  const cssExternal = [];
  const cssChunks = [];
  const jsChunks = [];

  for (const m of html.matchAll(/<script\s[^>]*?\bsrc="([^"]+)"[^>]*>/gi)) {
    jsExternal.push(m[1]);
  }

  for (const m of html.matchAll(/<link\b[^>]*?\brel=["']?stylesheet["']?[^>]*>/gi)) {
    const href = /\bhref="([^"]+)"/.exec(m[0]);
    if (href) cssExternal.push(href[1]);
  }

  for (const m of html.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/gi)) {
    if (m[1].trim()) cssChunks.push(m[1].trim());
  }

  // Inline scripts only — negative lookahead skips <script src="...">
  for (const m of html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi)) {
    if (m[1].trim()) jsChunks.push(m[1].trim());
  }

  const bodyMatch = html.match(/<body[^>]*>([\s\S]*?)<\/body>/i);
  const bodyHtml = bodyMatch ? bodyMatch[1].trim() : '';

  return {bodyHtml, css: cssChunks.join('\n\n'), js: jsChunks.join('\n\n'), jsExternal, cssExternal};
}

/**
 * Build a CodePen Prefill API payload.
 * Docs: https://blog.codepen.io/documentation/prefill/
 */
export function buildCodePenPrefill(html, title) {
  const {bodyHtml, css, js, jsExternal, cssExternal} = parseExample(html);
  return {
    title,
    description: 'Generated by deck.gl PR Validation Agent',
    html: bodyHtml,
    css,
    js,
    js_external: jsExternal.join(';'),
    css_external: cssExternal.join(';'),
    editors: '001',  // open to JS panel by default
  };
}

/**
 * Inject an "Open in CodePen" button into an HTML file.
 * The form-based POST works when opened from file:// — no server needed.
 */
export function injectCodePenButton(html, prefill) {
  const dataAttr = JSON.stringify(prefill)
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');

  const button = `
  <form action="https://codepen.io/pen/define" method="POST" target="_blank"
        style="position:absolute;top:10px;right:10px;z-index:1000;margin:0">
    <input type="hidden" name="data" value="${dataAttr}">
    <button type="submit"
            style="background:#1a1a2e;color:#89b4fa;border:1px solid #89b4fa;
                   padding:6px 14px;border-radius:4px;cursor:pointer;
                   font-size:13px;font-family:sans-serif">
      ✏️ Open in CodePen
    </button>
  </form>`;

  return html.replace(/(<body[^>]*>)/i, `$1\n${button}`);
}

/**
 * Generate a CodeSandbox define URL for direct linking from the PR comment.
 * Unlike CodePen, CodeSandbox accepts LZ-compressed parameters via GET.
 * Docs: https://codesandbox.io/docs/importing#define-api
 */
export function buildCodeSandboxUrl(html) {
  const parameters = LZString.compressToBase64(
    JSON.stringify({files: {'index.html': {content: html}}})
  );
  return `https://codesandbox.io/api/v1/sandboxes/define?parameters=${encodeURIComponent(parameters)}`;
}
