version: 2
sphinx:
  configuration: docs/conf.py
python:
  install:
    - method: pip
      path: .
build:
  os: "ubuntu-24.04"
  tools:
    python: "3.13"
  jobs:
    post_checkout:
      # CWD for readthedocs is repository root.
      - cp -r bindings/pydeck-carto/* .
    post_create_environment:
      - pip install uv
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv pip install --no-cache-dir -r requirements/requirements-dev.txt
